version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Install Vercel CLI locally
          command: pnpm install vercel
      - run:
          name: Deploy to Vercel
          command: |
            pnpm vercel pull --yes --token=$VERCEL_TOKEN

            echo "Length of NEXT_PUBLIC_SUPABASE_ANON_KEY: ${#NEXT_PUBLIC_SUPABASE_ANON_KEY}"
            echo "Length of NEXT_PUBLIC_SUPABASE_URL: ${#NEXT_PUBLIC_SUPABASE_URL}"
            echo "Length of VERCEL_TOKEN: ${#VERCEL_TOKEN}"

            # define vercel project name on deploy
            export VERCEL_PROJECT_NAME="solid-leaderboard-2"
            pnpm vercel link --project $VERCEL_PROJECT_NAME --token=$VERCEL_TOKEN --yes
            
            pnpm vercel deploy --yes --token=$VERCEL_TOKEN \
              --env NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
              --env NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL

workflows:
  deploy:
    jobs:
      - deploy